### PR TITLE
Revive HTMLPrettify

### PR DESCRIPTION
**Pull request by victorporof**
Initial approach to modernizing and consolidating some of this code. 

At the very least this once and for all fixes the misleading "nodejs not in the right path errors". For everything else, should have feature parity, but allowing more rapid iteration and adding new features.

To test, clone this branch.

To develop, `npm install` followed by `npm run build` on every change to the js code.

Any help testing this would be appreciated, especially on Windows and Linux, Sublime 2 and 3.

### CODE REVIEW

**Comment by victorporof** [comment]
User settings aren't now lost when plugin updates.

**Comment by victorporof** [comment]
Now using editor syntax by default for determining file type.

**Comment by victorporof** [comment]
Now able to ignore certain files using regexp.

**Comment by victorporof** [comment]
Added ability to use sublime's indentation settings instead of the ones in the .jsbeautifyrc file.

**Comment by victorporof** [comment]
Can now use different settings for js and json files.

**Comment by victorporof** [comment]
Added initial support for .editorconfig files.

**Comment by victorporof** [comment]
Major updates to the `.jsbeautifyrc` file format (backwards compatible): https://github.com/victorporof/Sublime-HTMLPrettify/tree/development#using-your-own-jsbeautifyrc-options

**Comment by victorporof** [comment]
Added the ability to automatically prettify while editing, opening files etc.

**Comment by ZaLiTHkA** [comment]
Wow... You've been busy hey @victorporof..?

I'm not much of a ST2 user, but I do use ST3 a great deal on both Linux Mint 18 at home and Windows 10 Pro at work. I'll update my Linux install this evening and my Windows install on Monday and let you know how things go.

Very excited for some of these changes.. :D

**Comment by victorporof** [comment]
@ZaLiTHkA Thanks a lot for testing!

**Comment by victorporof** [comment]
Added additional prettifier options: eol, comma_first and operator_position.

**Comment by victorporof** [comment]
RC1

**Comment by ZaLiTHkA** [comment]
Right... Off to a grand start.

So I cloned the repo, switched branches, then incorrectly symlinked it into ST3's `Packages` folder.. Then while trying to fix that, proceeded to completely clear the contents of my `Packages` folder. Lol.

Anyways, I repaired the damage and linked it properly using commit: a54fef880acb39a21a0e70312162eace79e4e88b

I've got a second instance of ST3 open to keep an eye on the console, and other than the initial "nodejs not found" message and me deliberately setting invalid keys and values in the `.editorconfig` file, I haven't seen any errors come up yet... I have seen some unexpected behaviour though, but I'm still working through those.

How do you want me to note down these strange things, should I perhaps create one new issue and describe them there?

**Comment by victorporof** [comment]
@ZaLiTHkA Just comment your findings in this PR. If there's any unexpected behavior I'll try to fix it before release.

If there's any additional features or diagnostic messages that would be helpful, let me know.

**Comment by victorporof** [comment]
@ZaLiTHkA Also, regarding "invalid keys" in the .editorconfig file, care to elaborate? I've added a translation function to map common editorconfig pref values to their jsbeautifyrc equivalents, and if there's more it's a good idea to add them: https://github.com/victorporof/Sublime-HTMLPrettify/blob/development/src/js/utils/configSanitizers.js#L70

**Comment by ZaLiTHkA** [comment]
Ok cool, will do. :)

I got caught up with some strange behaviour formatting stylesheets, which I ended up storing some notes [in this Gist](https://gist.github.com/ZaLiTHkA/b030b74d81a09f7842e1efe498e04bb1) anyway. So I think I'll just use that Gist to store snippets of code I use to test.

The "invalid keys and values" story was literally just me putting random things in the `.editorconfig` file; misspelled key names, incorrect key values; such as `end_of_line = l`, `indent_style = moon`, `cats = dogs`, etc. But it's cool, your plugin handled all that just fine.

Also, just a quick note: I'm heading out for a while this weekend, so I won't be able to get much more testing done today or tonight, but I am planning to spend some more time on this tomorrow afternoon again.

**Comment by victorporof** [comment]
RC2, fixed a bunch of papercuts.

**Comment by victorporof** [comment]
@ZaLiTHkA Thanks a bunch for your help!

**Comment by ZaLiTHkA** [comment]
So... Just noticed that I still have sindresorhus' [EditorConfig](https://packagecontrol.io/packages/EditorConfig) plugin installed; I'm not sure if there would be any conflict with the behaviour you're trying to implement here...

That plugin gives me syntax highlighting for `.editorconfig`, but it looks like it also tries to handle file processing. I use "Sync Settings" to keep a common editor configuration across a few different computers, so if you want, you can see my current config in [this Gist](https://gist.github.com/ZaLiTHkA/d511b53f177cb663e40a535119959c40).

Would you like me to remove sindresorhus' plugin before I continue testing yours..?

**Comment by victorporof** [comment]
@ZaLiTHkA I don't think there's going to be any incompatibilities between these plugins, but who knows!

**Comment by amit1911** [comment]
When is it going to be released?

**Comment by iamntz** [comment]
@amit1911 you can use it already by checking out the `development` branch.

@victorporof hey man, thanks for the plugin. It's great that you started to work on it again!

I just updated today and I noticed that when I'm trying to format, the `node.exe` window shows up for a couple of seconds:

node.exe

Also, the whole formatting thing it takes a couple of seconds as well.

Can you hide this and improve timing a bit? Emmet is also using Node and all operations are instant.

Thanks!

(ST build 3141, up to date windows 10)

**Comment by amit1911** [comment]
@iamntz thanks..i'll try that...
@victorporof any idea when are you going to release it?

**Comment by victorporof** [comment]
@amit1911 Releasing this as soon as all the papercuts are fixed. At this point you can contribute by checking out the development branch, testing it and letting me know what works and what doesn't.

@iamntz Thanks a bunch for the feedback, I'll look into it!

**Comment by amit1911** [comment]
Okay...thanks for all the good work... I am using the development branch now on sublime text 3. Will let you know if I encounter any bugs.

**Comment by ZaLiTHkA** [comment]
My Windows machine also pops up a CLI window when formatting, runs pretty quickly though (obviously depending on file size), hardly ever staying up for more than a second.

Still haven't had any issues with Linux, but I haven't had a chance to check this in on our MacMini just yet; if I get some time later today before I leave work, I'll drop this repo in the `Packages/` folder and see how it runs.

**Comment by victorporof** [comment]
The code for running external commands and invoking node is here: https://github.com/victorporof/Sublime-HTMLPrettify/blob/development/src/py/utils/env_utils.py

It used to be a giant mess. Old version: https://github.com/victorporof/Sublime-HTMLPrettify/blob/master/HTMLPrettify.py#L196

I'm not familiar enough with Python's intricacies between operating systems to figure out why the command prompt shows up, and I'd like to avoid switching back to the old messy way of doing things (and really... nobody knew how it actually worked).

**Comment by victorporof** [comment]
I'm stupid: 65b92e8

This should fix the commandprompt issue.

**Comment by victorporof** [comment]
@iamntz I made some tests and asked some people to try it out, and they reported similar findings to mine, which is less than a second for 1000 lines of json, and very similar performance with much larger files. Maybe hiding the commandprompt window makes things better?

I'm calling this RC3. It seems stable enough to release. Objections?

**Comment by iamntz** [comment]
Yup, the window doesn't pop up anymore, thanks!

I'm not sure that the performance per se is the problem, because it seems that it takes about the same time to run, no matter what the file size is. The delay seems to be due to the time it takes node to start, so I think it may be something wrong on _my_ machine with this one.

> I'm calling this RC3. It seems stable enough to release.
Sounds great! 👍

**Comment by victorporof** [comment]
Ideally in a future release we'll either: switch to the new python based jsbeautify and ditch node entirely, or start node once and treat it as a prettifier server that shuts down with the editor, not after every prettification.

**Comment by victorporof** [comment]
Release notes: https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.0.5

Thanks everyone for helping!

**Pull request merged**
